// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EDC_Automation.Features.DataLabs.ODM_Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DataLabs_V5.7.0_ODMEventingforStudyUpdatewithFlagandQueries")]
    public partial class DataLabs_V5_7_0_ODMEventingforStudyUpdatewithFlagandQueriesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ODMStudyUpdateFlaggingSignatureQueries.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DataLabs_V5.7.0_ODMEventingforStudyUpdatewithFlagandQueries", @"	Test Summary:
	1. Verification of ODM eventing xml for Study Update on Flag changes on Item
	2. Verification of ODM eventing xml for Study Update on Flag changes on Form
	3. Verification of ODM eventing xml for Study Update on Flag changes on Required and Non Required flag Items
	4. Verification of ODM eventing xml for Study Update on DCF created", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T01_Login to Datalabs")]
        public virtual void T01_LoginToDatalabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T01_Login to Datalabs", null, ((string[])(null)));
#line 10
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
 testRunner.Given("I logged in to DataLabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T02_Delete the current study")]
        public virtual void T02_DeleteTheCurrentStudy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T02_Delete the current study", null, ((string[])(null)));
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.When("I delete study", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I see study label \"No Study Loaded\" in header", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T03_Publish the study")]
        public virtual void T03_PublishTheStudy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T03_Publish the study", null, ((string[])(null)));
#line 18
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 19
 testRunner.When("I click breadcrumb \"Study Management\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("I upload a study \"Test3210_Flag_Base_01.Zip\" with study label \"TestBase\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("I see study label \"Test3210_Query Smoke Test\" in header", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T04_Create a SD Verify Plan with following DataGroups")]
        public virtual void T04_CreateASDVerifyPlanWithFollowingDataGroups()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T04_Create a SD Verify Plan with following DataGroups", null, ((string[])(null)));
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 24
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.And("I click Link \"Flag Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I select \"SD-Verify\" flag type from Flag Management page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I click Add Plan button to create a new plan.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I enter Plan Name as \"SDVPlan1\" and label as \"SDVPlanL1\" on Create Plan page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I click \"Next\" button on Create Plan page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I enter Data Group Name as \"SDVDG1\" and Data Group label as \"SDVDGL1\" on Create F" +
                    "lag Data Group page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FormName",
                        "QuestionNum",
                        "QuestionPrompt",
                        "ProtocolVersion"});
            table1.AddRow(new string[] {
                        "Form1",
                        "1.",
                        "Sample text question:",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Form 6",
                        "1.R.6.",
                        "Integer:",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Vital Signs",
                        "1.",
                        "Was exam performed?",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Vital Signs",
                        "3.",
                        "Time of Exam (24 hour clock):",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Vital Signs",
                        "6.",
                        "Weight Units:",
                        "1.0"});
            table1.AddRow(new string[] {
                        "Vital Signs",
                        "13.",
                        "Temperature Method:",
                        "1.0"});
#line 31
 testRunner.And("I select checkbox for form questions in protocol version.", ((string)(null)), table1, "And ");
#line 39
 testRunner.And("I click \"Next\" button on Create Flag Data Group page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I click on Save & Close button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.Then("I verify the success message displayed as \"Plan saved successfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T05_Assign Plan to Study")]
        public virtual void T05_AssignPlanToStudy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T05_Assign Plan to Study", null, ((string[])(null)));
#line 43
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 44
 testRunner.When("I select the \"Assign Plan to Study\" link on the Manage Plans & Flag Data Groups p" +
                    "age.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.And("I select \"SDVPlanL1 (3%)\" in the Select Plan dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.When("I select \"Entry correction\" in Reason for change dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.When("I enter text \"New SDV FLag\" in Additional Notes text box.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.When("I click \"Save\" button on Assign Plan to Study page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I verify the success message displayed as \"Plan assigned successfully.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T06_Add Site 01-Site and assign it to testadmin user")]
        public virtual void T06_AddSite01_SiteAndAssignItToTestadminUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T06_Add Site 01-Site and assign it to testadmin user", null, ((string[])(null)));
#line 51
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 52
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "SiteId",
                        "SiteName",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Address4",
                        "City",
                        "State",
                        "Zip",
                        "ISOCountry",
                        "Country",
                        "Phone",
                        "Fax",
                        "SiteStatus",
                        "DCFWorkflow",
                        "ExternalSource",
                        "ExternalId"});
            table2.AddRow(new string[] {
                        "01",
                        "Site",
                        "ADDRESS",
                        "ADDRESS",
                        "ADDRESS",
                        "ADDRESS",
                        "Hyderabad",
                        "AP",
                        "500060",
                        "INDIA(IND)",
                        "",
                        "9999999999",
                        "66666666666",
                        "Active",
                        "Electronic",
                        "No",
                        "-"});
#line 54
 testRunner.And("I enter sites details and Save", ((string)(null)), table2, "And ");
#line 57
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I click ActionPalette Item \"Manage Users\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I add and save user \"testadmin testadmin\" to site users in SiteManageUsersPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.Then("I see Site details page for \"01-Site\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T07_Navigate to the Edit Preferences page and set the CRF Default save to Complet" +
            "e and update the Endpoint URL")]
        public virtual void T07_NavigateToTheEditPreferencesPageAndSetTheCRFDefaultSaveToCompleteAndUpdateTheEndpointURL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T07_Navigate to the Edit Preferences page and set the CRF Default save to Complet" +
                    "e and update the Endpoint URL", null, ((string[])(null)));
#line 62
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 63
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.When("I click Link \"Study Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.And("I click ActionPalette Item \"Edit Preferences\" in \"StudyResetAction\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("I open tab \"Forms\" in StudyEditPreferencesPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.And("I select the \"Partial\" for Default Save: in StudyEditPreferencesFormsPage.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I open tab \"patient data eventing\" in StudyEditPreferencesPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I update the endpoint URL under Patient Data Eventing tab.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("I click \"Save\" button on the Edit Preferences page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.Then("I verify the success message displayed as \"Edit Preferences Successful\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T08_Add patient 001-Patient from Datalabs UI")]
        public virtual void T08_AddPatient001_PatientFromDatalabsUI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T08_Add patient 001-Patient from Datalabs UI", null, ((string[])(null)));
#line 73
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 74
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScreenID",
                        "PatientInitials",
                        "ScreenDate"});
            table3.AddRow(new string[] {
                        "001",
                        "Patient",
                        "09/04/2018"});
#line 76
 testRunner.When("I add patient with below details.", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table4.AddRow(new string[] {
                        "001-Patient"});
#line 79
 testRunner.Then("I see below patients added in the Patients table.", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T09_Select and enroll patient 001-Patient.")]
        public virtual void T09_SelectAndEnrollPatient001_Patient_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T09_Select and enroll patient 001-Patient.", null, ((string[])(null)));
#line 83
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 84
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I select the patient \"001-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EnrollID",
                        "EnrollDate",
                        "EntryComplete"});
            table5.AddRow(new string[] {
                        "001",
                        "09/04/2018",
                        "Yes"});
#line 87
 testRunner.When("I enroll the patient \"001-Patient\" with below data.", ((string)(null)), table5, "When ");
#line 90
 testRunner.Then("I see patient \"001-Patient\" status as \"Enrolled\" on Patient details page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T10_Add patient 002-Patient from Datalabs UI")]
        public virtual void T10_AddPatient002_PatientFromDatalabsUI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T10_Add patient 002-Patient from Datalabs UI", null, ((string[])(null)));
#line 92
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 93
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScreenID",
                        "PatientInitials",
                        "ScreenDate"});
            table6.AddRow(new string[] {
                        "002",
                        "Patient",
                        "09/04/2018"});
#line 95
 testRunner.When("I add patient with below details.", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table7.AddRow(new string[] {
                        "002-Patient"});
#line 98
 testRunner.Then("I see below patients added in the Patients table.", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T11_Select and enroll patient 002-Patient.")]
        public virtual void T11_SelectAndEnrollPatient002_Patient_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T11_Select and enroll patient 002-Patient.", null, ((string[])(null)));
#line 102
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 103
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("I select the patient \"002-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "EnrollID",
                        "EnrollDate",
                        "EntryComplete"});
            table8.AddRow(new string[] {
                        "002",
                        "09/04/2018",
                        "Yes"});
#line 106
 testRunner.When("I enroll the patient \"002-Patient\" with below data.", ((string)(null)), table8, "When ");
#line 109
 testRunner.Then("I see patient \"002-Patient\" status as \"Enrolled\" on Patient details page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T12_Add patient 003-Patient from Datalabs UI")]
        public virtual void T12_AddPatient003_PatientFromDatalabsUI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T12_Add patient 003-Patient from Datalabs UI", null, ((string[])(null)));
#line 111
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 112
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScreenID",
                        "PatientInitials",
                        "ScreenDate"});
            table9.AddRow(new string[] {
                        "003",
                        "Patient",
                        "09/04/2018"});
#line 114
 testRunner.When("I add patient with below details.", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table10.AddRow(new string[] {
                        "003-Patient"});
#line 117
 testRunner.Then("I see below patients added in the Patients table.", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T13_Select and enroll patient 003-Patient.")]
        public virtual void T13_SelectAndEnrollPatient003_Patient_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T13_Select and enroll patient 003-Patient.", null, ((string[])(null)));
#line 121
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 122
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 123
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.And("I select the patient \"003-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "EnrollID",
                        "EnrollDate",
                        "EntryComplete"});
            table11.AddRow(new string[] {
                        "003",
                        "09/04/2018",
                        "Yes"});
#line 125
 testRunner.When("I enroll the patient \"003-Patient\" with below data.", ((string)(null)), table11, "When ");
#line 128
 testRunner.Then("I see patient \"003-Patient\" status as \"Enrolled\" on Patient details page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T14_Add patient 004-Patient from Datalabs UI.")]
        public virtual void T14_AddPatient004_PatientFromDatalabsUI_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T14_Add patient 004-Patient from Datalabs UI.", null, ((string[])(null)));
#line 130
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 131
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScreenID",
                        "PatientInitials",
                        "ScreenDate"});
            table12.AddRow(new string[] {
                        "004",
                        "Patient",
                        "09/04/2018"});
#line 133
 testRunner.When("I add patient with below details.", ((string)(null)), table12, "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table13.AddRow(new string[] {
                        "004-Patient"});
#line 136
 testRunner.Then("I see below patients added in the Patients table.", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T15_Select and enroll patient 004-Patient.")]
        public virtual void T15_SelectAndEnrollPatient004_Patient_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T15_Select and enroll patient 004-Patient.", null, ((string[])(null)));
#line 140
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 141
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("I select the patient \"004-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "EnrollID",
                        "EnrollDate",
                        "EntryComplete"});
            table14.AddRow(new string[] {
                        "004",
                        "09/04/2018",
                        "Yes"});
#line 144
 testRunner.When("I enroll the patient \"004-Patient\" with below data.", ((string)(null)), table14, "When ");
#line 147
 testRunner.Then("I see patient \"004-Patient\" status as \"Enrolled\" on Patient details page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T16_Select Visit(Screening) - Form1 under patient 001-Patient, Enter Data and Sub" +
            "mit")]
        public virtual void T16_SelectVisitScreening_Form1UnderPatient001_PatientEnterDataAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T16_Select Visit(Screening) - Form1 under patient 001-Patient, Enter Data and Sub" +
                    "mit", null, ((string[])(null)));
#line 149
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 150
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 151
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.And("I select the patient \"001-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 153
 testRunner.And("I expand \"Visit (Screening)\" to select and open \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.When("I select \"Checkout\" button on \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType"});
            table15.AddRow(new string[] {
                        "Sample text question:",
                        "Text",
                        "Textbox"});
#line 155
 testRunner.And("I enter below flat questions data in the CRF.", ((string)(null)), table15, "And ");
#line 158
 testRunner.And("I select \"Save\" button on \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T17_Select Flag On for the Form for Question Sample text question")]
        public virtual void T17_SelectFlagOnForTheFormForQuestionSampleTextQuestion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T17_Select Flag On for the Form for Question Sample text question", null, ((string[])(null)));
#line 161
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review"});
            table16.AddRow(new string[] {
                        "Sample text question:",
                        "On",
                        "",
                        ""});
#line 162
 testRunner.When("I set flag for below flat questions data in the CRFs.", ((string)(null)), table16, "When ");
#line 165
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" against question \"Sample text" +
                    " question:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T18_Select Visit (Week 2) - Form6 and enter value for Question and submit")]
        public virtual void T18_SelectVisitWeek2_Form6AndEnterValueForQuestionAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T18_Select Visit (Week 2) - Form6 and enter value for Question and submit", null, ((string[])(null)));
#line 167
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 168
 testRunner.Given("I click breadcrumb \"001-Patient\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.And("I expand \"Visit (Week 2)\" to select and open \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType",
                        "RowButtonToClick"});
            table17.AddRow(new string[] {
                        "Yes",
                        "1",
                        "Integer:",
                        "3",
                        "Textbox",
                        "Save & Close Row"});
#line 171
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table17, "And ");
#line 174
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T19_Select SD-Verify Flag On for the Question Integer for the Form 6")]
        public virtual void T19_SelectSD_VerifyFlagOnForTheQuestionIntegerForTheForm6()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T19_Select SD-Verify Flag On for the Question Integer for the Form 6", null, ((string[])(null)));
#line 177
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "RowNumber",
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review",
                        "RowButtonToClick"});
            table18.AddRow(new string[] {
                        "1",
                        "Integer:",
                        "On",
                        "",
                        "",
                        ""});
#line 178
 testRunner.When("I set flag for below \"Table with All Data Types:\" table questions data in the CRF" +
                    "s.", ((string)(null)), table18, "When ");
#line 181
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" of a question \"Integer:\" of t" +
                    "able \"Table with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T20_Select Visit (Week 3) - Vital Signs form, enter data and submit")]
        public virtual void T20_SelectVisitWeek3_VitalSignsFormEnterDataAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T20_Select Visit (Week 3) - Vital Signs form, enter data and submit", null, ((string[])(null)));
#line 183
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 184
 testRunner.Given("I click breadcrumb \"001-Patient\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 185
 testRunner.And("I expand \"Visit (Week 3)\" to select and open \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.When("I select \"Checkout\" button on \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType"});
            table19.AddRow(new string[] {
                        "Was exam performed?",
                        "Yes",
                        "LISTBOX"});
            table19.AddRow(new string[] {
                        "Time of Exam (24 hour clock):",
                        "08",
                        "LISTBOX"});
            table19.AddRow(new string[] {
                        "Weight Units:",
                        "KG",
                        "LISTBOX"});
            table19.AddRow(new string[] {
                        "Temperature Method:&#x20",
                        "Auxillary",
                        "LISTBOX"});
#line 187
 testRunner.And("I enter below data for Flat questions in CRF.", ((string)(null)), table19, "And ");
#line 193
 testRunner.And("I select \"Save\" button on \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T21_Select flagging for the below questions")]
        public virtual void T21_SelectFlaggingForTheBelowQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T21_Select flagging for the below questions", null, ((string[])(null)));
#line 196
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 197
 testRunner.When("I click link \"Mark Required\" for the flag type \"SD-Verify\" in FlagPalette of CRF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
 testRunner.Then("I see success message \"M-Review On\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 199
 testRunner.And("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" against question \"Was exam pe" +
                    "rformed?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.And("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" against question \"Time of Exa" +
                    "m (24 hour clock):\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.And("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" against question \"Weight Unit" +
                    "s:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.And("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" against question \"Temperature" +
                    " Method:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T22_Select patient 002-Patient, Select Form 6 under visit (Week 2) submit the que" +
            "stion Integer")]
        public virtual void T22_SelectPatient002_PatientSelectForm6UnderVisitWeek2SubmitTheQuestionInteger()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T22_Select patient 002-Patient, Select Form 6 under visit (Week 2) submit the que" +
                    "stion Integer", null, ((string[])(null)));
#line 205
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 206
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 207
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I select the patient \"002-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And("I expand \"Visit (Week 2)\" to select and open \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType",
                        "RowButtonToClick"});
            table20.AddRow(new string[] {
                        "Yes",
                        "1",
                        "Integer:",
                        "4",
                        "Textbox",
                        "Save & Close Row"});
#line 211
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table20, "And ");
#line 214
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "RowNumber",
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review",
                        "RowButtonToClick"});
            table21.AddRow(new string[] {
                        "1",
                        "Integer:",
                        "On",
                        "",
                        "",
                        ""});
#line 215
 testRunner.When("I set flag for below \"Table with All Data Types:\" table questions data in the CRF" +
                    "s.", ((string)(null)), table21, "When ");
#line 218
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_required_set.gif\" of a question \"Integer:\" of t" +
                    "able \"Table with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T23_Select Checkout and update the value for Integer Question")]
        public virtual void T23_SelectCheckoutAndUpdateTheValueForIntegerQuestion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T23_Select Checkout and update the value for Integer Question", null, ((string[])(null)));
#line 220
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 221
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "CurrentAnswerValue",
                        "ReasonForChange",
                        "AnswerFieldType",
                        "NewAnswerValue",
                        "RowButtonToClick"});
            table22.AddRow(new string[] {
                        "No",
                        "1",
                        "Integer:",
                        "4",
                        "DCF",
                        "Textbox",
                        "5",
                        "Save & Close Row"});
#line 222
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table22, "And ");
#line 225
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
 testRunner.And("I expand row \"1\" of table \"Table with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_required_changed.gif\" of a question \"Integer:\" " +
                    "of table \"Table with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T24_Select Visit(Screening) - Form1 under patient 003-Patient, Enter Data and Sub" +
            "mit")]
        public virtual void T24_SelectVisitScreening_Form1UnderPatient003_PatientEnterDataAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T24_Select Visit(Screening) - Form1 under patient 003-Patient, Enter Data and Sub" +
                    "mit", null, ((string[])(null)));
#line 230
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 231
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 232
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I select the patient \"003-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I expand \"Visit (Screening)\" to select and open \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.When("I select \"Checkout\" button on \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType"});
            table23.AddRow(new string[] {
                        "Sample select question:",
                        "Yes",
                        "LISTBOX"});
#line 236
 testRunner.And("I enter below flat questions data in the CRF.", ((string)(null)), table23, "And ");
#line 239
 testRunner.And("I select \"Save\" button on \"Form1\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T25_Select Flag On for the Form for Question Sample select question")]
        public virtual void T25_SelectFlagOnForTheFormForQuestionSampleSelectQuestion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T25_Select Flag On for the Form for Question Sample select question", null, ((string[])(null)));
#line 242
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review"});
            table24.AddRow(new string[] {
                        "Sample select question:",
                        "",
                        "On",
                        ""});
#line 243
 testRunner.When("I set flag for below flat questions data in the CRFs.", ((string)(null)), table24, "When ");
#line 246
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_set.gif\" against question \"Sample select questi" +
                    "on:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T26_Select Visit (Week 2) - Form6 and enter value for Question and submit")]
        public virtual void T26_SelectVisitWeek2_Form6AndEnterValueForQuestionAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T26_Select Visit (Week 2) - Form6 and enter value for Question and submit", null, ((string[])(null)));
#line 248
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 249
 testRunner.Given("I click breadcrumb \"003-Patient\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 250
 testRunner.And("I expand \"Visit (Week 2)\" to select and open \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 251
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType",
                        "RowButtonToClick"});
            table25.AddRow(new string[] {
                        "Yes",
                        "1",
                        "Float:",
                        "11.11",
                        "Textbox",
                        "Save & Close Row"});
#line 252
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table25, "And ");
#line 255
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 256
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T27_Select SD-Verify Flag On for the Question Integer for the Form 6")]
        public virtual void T27_SelectSD_VerifyFlagOnForTheQuestionIntegerForTheForm6()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T27_Select SD-Verify Flag On for the Question Integer for the Form 6", null, ((string[])(null)));
#line 258
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "RowNumber",
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review",
                        "RowButtonToClick"});
            table26.AddRow(new string[] {
                        "1",
                        "Float:",
                        "",
                        "On",
                        "",
                        ""});
#line 259
 testRunner.When("I set flag for below \"Table with All Data Types:\" table questions data in the CRF" +
                    "s.", ((string)(null)), table26, "When ");
#line 262
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_set.gif\" of a question \"Float:\" of table \"Table" +
                    " with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T28_Select Visit (Week 3) - Vital Signs form, enter data and submit")]
        public virtual void T28_SelectVisitWeek3_VitalSignsFormEnterDataAndSubmit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T28_Select Visit (Week 3) - Vital Signs form, enter data and submit", null, ((string[])(null)));
#line 264
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 265
 testRunner.Given("I click breadcrumb \"003-Patient\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 266
 testRunner.And("I expand \"Visit (Week 3)\" to select and open \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.When("I select \"Checkout\" button on \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType"});
            table27.AddRow(new string[] {
                        "Was exam performed?",
                        "Yes",
                        "LISTBOX"});
            table27.AddRow(new string[] {
                        "Time of Exam (minutes):",
                        "01",
                        "LISTBOX"});
            table27.AddRow(new string[] {
                        "Height Units:",
                        "in",
                        "LISTBOX"});
#line 268
 testRunner.And("I enter below data for Flat questions in CRF.", ((string)(null)), table27, "And ");
#line 273
 testRunner.And("I select \"Save\" button on \"Vital Signs\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.Then("I verify the success message displayed as \"CRF has been saved and checked in succ" +
                    "essfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T29_Select flagging for the below questions")]
        public virtual void T29_SelectFlaggingForTheBelowQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T29_Select flagging for the below questions", null, ((string[])(null)));
#line 276
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review"});
            table28.AddRow(new string[] {
                        "Time of Exam (minutes):",
                        "",
                        "On",
                        ""});
            table28.AddRow(new string[] {
                        "Height Units:",
                        "",
                        "On",
                        ""});
#line 277
 testRunner.When("I set flag for below flat questions data in the CRFs.", ((string)(null)), table28, "When ");
#line 281
 testRunner.Then("I see flag \"M-Review\" icon \"flag_set.gif\" against question \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 282
 testRunner.And("I see flag \"M-Review\" icon \"flag_set.gif\" against question \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T30_Select patient 004-Patient, Select Form 6 under visit (Week 2) submit the que" +
            "stion Integer")]
        public virtual void T30_SelectPatient004_PatientSelectForm6UnderVisitWeek2SubmitTheQuestionInteger()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T30_Select patient 004-Patient, Select Form 6 under visit (Week 2) submit the que" +
                    "stion Integer", null, ((string[])(null)));
#line 285
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 286
 testRunner.Given("I navigate to \"Patients\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 287
 testRunner.And("I select the site \"01-Site\" from Sites dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 288
 testRunner.And("I select the patient \"004-Patient\" from patients table.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 289
 testRunner.And("I expand \"Visit (Week 2)\" to select and open \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 290
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "AnswerValue",
                        "AnswerFieldType",
                        "RowButtonToClick"});
            table29.AddRow(new string[] {
                        "Yes",
                        "1",
                        "Float:",
                        "12.21",
                        "Textbox",
                        "Save & Close Row"});
#line 291
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table29, "And ");
#line 294
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "RowNumber",
                        "QuestionPrompt",
                        "SD-Verify",
                        "M-Review",
                        "D-Review",
                        "RowButtonToClick"});
            table30.AddRow(new string[] {
                        "1",
                        "Float:",
                        "",
                        "On",
                        "",
                        ""});
#line 295
 testRunner.When("I set flag for below \"Table with All Data Types:\" table questions data in the CRF" +
                    "s.", ((string)(null)), table30, "When ");
#line 298
 testRunner.Then("I see flag \"SD-Verify\" icon \"flag_set.gif\" of a question \"Integer:\" of table \"Tab" +
                    "le with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T31_Select Checkout and update the value for Integer Question")]
        public virtual void T31_SelectCheckoutAndUpdateTheValueForIntegerQuestion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T31_Select Checkout and update the value for Integer Question", null, ((string[])(null)));
#line 300
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 301
 testRunner.When("I select \"Checkout\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "AddNewRow",
                        "RowNumber",
                        "QuestionPrompt",
                        "CurrentAnswerValue",
                        "ReasonForChange",
                        "AnswerFieldType",
                        "NewAnswerValue",
                        "RowButtonToClick"});
            table31.AddRow(new string[] {
                        "No",
                        "1",
                        "Float:",
                        "12.21",
                        "DCF",
                        "Textbox",
                        "13.33",
                        "Save & Close Row"});
#line 302
 testRunner.And("I enter below \"Table with All Data Types:\" table questions data in the CRF.", ((string)(null)), table31, "And ");
#line 305
 testRunner.And("I select \"Save\" button on \"Form 6\" CRF.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 306
 testRunner.And("I expand row \"1\" of table \"Table with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 307
 testRunner.Then("I see flag \"M-Review\" icon \"flag_changed.gif\" of a question \"Float:\" of table \"Ta" +
                    "ble with All Data Types:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T32_Update study with patients migration")]
        public virtual void T32_UpdateStudyWithPatientsMigration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T32_Update study with patients migration", null, ((string[])(null)));
#line 309
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 310
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 311
 testRunner.And("I click Link \"Study Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.And("I click ActionPalette Item \"Manage Versions\" in \"StudyResetAction\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 313
 testRunner.And("I click ActionPalette Item \"Upload Study File\" in \"StudyVersionMgmtListActions\" A" +
                    "ctionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 314
 testRunner.And("I click browse button in upload study file page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 315
 testRunner.And("I upload study \"Test3210_Flag_Update_02.zip\" with Label \"UpdateFlag\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 316
 testRunner.And("I open study which has \"Uploaded\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 317
 testRunner.And("I click ActionPalette Item \"Stage\" in \"StudyVersionPropertiesActions\" ActionPalet" +
                    "te", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 318
 testRunner.And("I open study which has \"Staged\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 319
 testRunner.And("I click ActionPalette Item \"Publish\" in \"StudyVersionPropertiesActions\" ActionPal" +
                    "ette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 320
 testRunner.And("I select \"Yes\" to reevaluate \"Change SD-Verify Flags?\" in PublishStudyFlagsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 321
 testRunner.And("I select \"Yes\" to reevaluate \"Change D-Review Flags?\" in PublishStudyFlagsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 322
 testRunner.And("I select \"Yes\" to reevaluate \"Change M-Review Flags?\" in PublishStudyFlagsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 323
 testRunner.And("I select \"Yes\" to reevaluate \"Change Signatures?\" in PublishStudyFlagsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 324
 testRunner.And("I clicked Continue button in PublishStudyFlagsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 325
 testRunner.And("I select patient migration option \"Do not migrate\" in PublishStudyPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 326
 testRunner.And("I click Publish button in PublishStudyPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
 testRunner.And("I navigate to \"Inbox\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table32.AddRow(new string[] {
                        "Study file (UpdateFlag) - complete."});
#line 328
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table32, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T33_Migrate Patient 001-Patient from Site Management")]
        public virtual void T33_MigratePatient001_PatientFromSiteManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T33_Migrate Patient 001-Patient from Site Management", null, ((string[])(null)));
#line 332
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 333
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 334
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 335
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.And("I click ActionPalette Item \"Migrate Patients\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table33.AddRow(new string[] {
                        "001-Patient"});
#line 337
 testRunner.And("I select patients in MigratePatientsPage", ((string)(null)), table33, "And ");
#line 340
 testRunner.And("I click save button in MigratePatientsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 341
 testRunner.And("I navigate to \"Inbox\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table34.AddRow(new string[] {
                        "Migration of Site 01 for Study file (UpdateFlag) - complete. 1 out of 1 patients " +
                            "migrated successfully. To review see migration report."});
#line 342
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table34, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T34_Verify the XML Data evented out via Study Update for Patient 001-Patient")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqID:3.1.6.1,3.1.6.2,3.1.6.8")]
        public virtual void T34_VerifyTheXMLDataEventedOutViaStudyUpdateForPatient001_Patient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T34_Verify the XML Data evented out via Study Update for Patient 001-Patient", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqID:3.1.6.1,3.1.6.2,3.1.6.8"});
#line 346
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 347
 testRunner.Given("I save the Event XML data in \"StudyUpdateFlagUpdatePatient001Actual.xml\" file by " +
                    "executing the query \"Select Top 1 XmlMessage from OdmSubscriberDetail where Stud" +
                    "yEventKey=16 order by OdmSubscriberDetailKey desc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 348
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient001Expected.xml\" available in th" +
                    "e project folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 349
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient001Actual.xml\" available in the " +
                    "Test XML Files folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "TagName",
                        "FieldName"});
            table35.AddRow(new string[] {
                        "",
                        "CreationDateTime"});
            table35.AddRow(new string[] {
                        "",
                        "DateTimeStamp"});
            table35.AddRow(new string[] {
                        "",
                        "SubjectKey"});
            table35.AddRow(new string[] {
                        "",
                        "FileOID"});
            table35.AddRow(new string[] {
                        "",
                        "SourceID"});
            table35.AddRow(new string[] {
                        "",
                        "QueryOID"});
            table35.AddRow(new string[] {
                        "",
                        "SourceSystemVersion"});
#line 350
 testRunner.Then("I verify that the data in both XML files is same except for below tags and fields" +
                    ".", ((string)(null)), table35, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T35_Migrate Patient 002-Patient from Site Management")]
        public virtual void T35_MigratePatient002_PatientFromSiteManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T35_Migrate Patient 002-Patient from Site Management", null, ((string[])(null)));
#line 360
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 361
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 362
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
 testRunner.And("I click ActionPalette Item \"Migrate Patients\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table36.AddRow(new string[] {
                        "002-Patient"});
#line 365
 testRunner.And("I select patients in MigratePatientsPage", ((string)(null)), table36, "And ");
#line 368
 testRunner.And("I click save button in MigratePatientsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 369
 testRunner.And("I navigate to \"Inbox\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table37.AddRow(new string[] {
                        "Migration of Site 01 for Study file (UpdateFlag) - complete. 1 out of 1 patients " +
                            "migrated successfully. To review see migration report."});
#line 370
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table37, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T36_Verify the XML Data evented out via Study Update for Patient 002-Patient")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqID:3.1.6.1,3.1.6.2,3.1.6.9")]
        public virtual void T36_VerifyTheXMLDataEventedOutViaStudyUpdateForPatient002_Patient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T36_Verify the XML Data evented out via Study Update for Patient 002-Patient", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqID:3.1.6.1,3.1.6.2,3.1.6.9"});
#line 375
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 376
 testRunner.Given("I save the Event XML data in \"StudyUpdateFlagUpdatePatient002Actual.xml\" file by " +
                    "executing the query \"Select Top 1 XmlMessage from OdmSubscriberDetail where Stud" +
                    "yEventKey=16 order by OdmSubscriberDetailKey desc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 377
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient002Expected.xml\" available in th" +
                    "e project folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 378
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient002Actual.xml\" available in the " +
                    "Test XML Files folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "TagName",
                        "FieldName"});
            table38.AddRow(new string[] {
                        "",
                        "CreationDateTime"});
            table38.AddRow(new string[] {
                        "",
                        "DateTimeStamp"});
            table38.AddRow(new string[] {
                        "",
                        "SubjectKey"});
            table38.AddRow(new string[] {
                        "",
                        "FileOID"});
            table38.AddRow(new string[] {
                        "",
                        "SourceID"});
            table38.AddRow(new string[] {
                        "",
                        "QueryOID"});
            table38.AddRow(new string[] {
                        "",
                        "SourceSystemVersion"});
#line 379
 testRunner.Then("I verify that the data in both XML files is same except for below tags and fields" +
                    ".", ((string)(null)), table38, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T37_Migrate Patient 003-Patient from Site Management")]
        public virtual void T37_MigratePatient003_PatientFromSiteManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T37_Migrate Patient 003-Patient from Site Management", null, ((string[])(null)));
#line 390
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 391
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 392
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 393
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 394
 testRunner.And("I click ActionPalette Item \"Migrate Patients\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table39.AddRow(new string[] {
                        "003-Patient"});
#line 395
 testRunner.And("I select patients in MigratePatientsPage", ((string)(null)), table39, "And ");
#line 398
 testRunner.And("I click save button in MigratePatientsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.And("I navigate to \"Inbox\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table40.AddRow(new string[] {
                        "Migration of Site 01 for Study file (UpdateFlag) - complete. 1 out of 1 patients " +
                            "migrated successfully. To review see migration report."});
#line 400
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table40, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T38_Verify the XML Data evented out via Study Update for Patient 003-Patient")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqID:3.1.6.1,3.1.6.2,3.1.6.8")]
        public virtual void T38_VerifyTheXMLDataEventedOutViaStudyUpdateForPatient003_Patient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T38_Verify the XML Data evented out via Study Update for Patient 003-Patient", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqID:3.1.6.1,3.1.6.2,3.1.6.8"});
#line 405
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 406
 testRunner.Given("I save the Event XML data in \"StudyUpdateFlagUpdatePatient003Actual.xml\" file by " +
                    "executing the query \"Select Top 1 XmlMessage from OdmSubscriberDetail where Stud" +
                    "yEventKey=16 order by OdmSubscriberDetailKey desc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 407
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient003Expected.xml\" available in th" +
                    "e project folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 408
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient003Actual.xml\" available in the " +
                    "Test XML Files folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "TagName",
                        "FieldName"});
            table41.AddRow(new string[] {
                        "",
                        "CreationDateTime"});
            table41.AddRow(new string[] {
                        "",
                        "DateTimeStamp"});
            table41.AddRow(new string[] {
                        "",
                        "SubjectKey"});
            table41.AddRow(new string[] {
                        "",
                        "FileOID"});
            table41.AddRow(new string[] {
                        "",
                        "SourceID"});
            table41.AddRow(new string[] {
                        "",
                        "QueryOID"});
            table41.AddRow(new string[] {
                        "",
                        "SourceSystemVersion"});
#line 409
 testRunner.Then("I verify that the data in both XML files is same except for below tags and fields" +
                    ".", ((string)(null)), table41, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T39_Migrate Patient 004-Patient from Site Management")]
        public virtual void T39_MigratePatient004_PatientFromSiteManagement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T39_Migrate Patient 004-Patient from Site Management", null, ((string[])(null)));
#line 420
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 421
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 422
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 423
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 424
 testRunner.And("I click ActionPalette Item \"Migrate Patients\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "PatientID"});
            table42.AddRow(new string[] {
                        "004-Patient"});
#line 425
 testRunner.And("I select patients in MigratePatientsPage", ((string)(null)), table42, "And ");
#line 428
 testRunner.And("I click save button in MigratePatientsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 429
 testRunner.And("I navigate to \"Inbox\" tab from main menu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table43.AddRow(new string[] {
                        "Migration of Site 01 for Study file (UpdateFlag) - complete. 1 out of 1 patients " +
                            "migrated successfully. To review see migration report."});
#line 430
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table43, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("T40_Verify the XML Data evented out via Study Update for Patient 004-Patient")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqID:3.1.6.1,3.1.6.2,3.1.6.9")]
        public virtual void T40_VerifyTheXMLDataEventedOutViaStudyUpdateForPatient004_Patient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("T40_Verify the XML Data evented out via Study Update for Patient 004-Patient", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqID:3.1.6.1,3.1.6.2,3.1.6.9"});
#line 435
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 436
 testRunner.Given("I save the Event XML data in \"StudyUpdateFlagUpdatePatient004Actual.xml\" file by " +
                    "executing the query \"Select Top 1 XmlMessage from OdmSubscriberDetail where Stud" +
                    "yEventKey=16 order by OdmSubscriberDetailKey desc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 437
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient004Expected.xml\" available in th" +
                    "e project folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 438
 testRunner.And("I have the XML file \"StudyUpdateFlagUpdatePatient004Actual.xml\" available in the " +
                    "Test XML Files folder.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "TagName",
                        "FieldName"});
            table44.AddRow(new string[] {
                        "",
                        "CreationDateTime"});
            table44.AddRow(new string[] {
                        "",
                        "DateTimeStamp"});
            table44.AddRow(new string[] {
                        "",
                        "SubjectKey"});
            table44.AddRow(new string[] {
                        "",
                        "FileOID"});
            table44.AddRow(new string[] {
                        "",
                        "SourceID"});
            table44.AddRow(new string[] {
                        "",
                        "QueryOID"});
            table44.AddRow(new string[] {
                        "",
                        "SourceSystemVersion"});
#line 439
 testRunner.Then("I verify that the data in both XML files is same except for below tags and fields" +
                    ".", ((string)(null)), table44, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

