#error (1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'US US47452_Authoring BDD scenarios for patient state change'
#error (3:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'An ODM 1.3.2 file should generate when a patient state is successfully through UI.'
#error (5:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: T01_Login to Datalabs'
#error (6:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given I logged in to DataLabs'
#error (7:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Then I see Datalabs Home Page'
#error (9:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: T02_Publish a study'
#error (10:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'When I click breadcrumb "Study Management"'
#error (11:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I upload a study "Base Study V1" with study label "L1"'
#error (12:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Then I see study label "Test3210" in header'
#error (14:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: T03_Add Sites'
#error (15:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'When I select DataManagerPortal item "Study Administration" from drop down'