// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EDC_Automation.Features.DataLabs.Labs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Labs_GroupPermissions")]
    public partial class Labs_GroupPermissionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Labs_GroupPermissions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Labs_GroupPermissions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("00_Login to Datalabs")]
        [NUnit.Framework.CategoryAttribute("updated")]
        [NUnit.Framework.CategoryAttribute("as")]
        [NUnit.Framework.CategoryAttribute("per")]
        [NUnit.Framework.CategoryAttribute("US52149")]
        public virtual void _00_LoginToDatalabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("00_Login to Datalabs", null, new string[] {
                        "updated",
                        "as",
                        "per",
                        "US52149"});
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given("I logged in to DataLabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01_Navigate to StudyAdministrationPage And GroupManagementPage")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.1")]
        public virtual void _01_NavigateToStudyAdministrationPageAndGroupManagementPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01_Navigate to StudyAdministrationPage And GroupManagementPage", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.1"});
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I see expanded PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PermissionName",
                        "Allow",
                        "Deny",
                        "Hide",
                        "View",
                        "Edit"});
            table1.AddRow(new string[] {
                        "Associate Lab(s) to Site",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
#line 15
 testRunner.And("I validate GroupPermissionsData for the premissons group \"Site Permissions\"", ((string)(null)), table1, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02_Check Default values for Lab Permissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.1,US36590.2,US36590.3,US36590.4,US36590.5,US36590.6")]
        public virtual void _02_CheckDefaultValuesForLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02_Check Default values for Lab Permissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.1,US36590.2,US36590.3,US36590.4,US36590.5,US36590.6"});
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 21
 testRunner.When("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I see expanded PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PermissionName",
                        "Allow",
                        "Deny",
                        "Hide",
                        "View",
                        "Edit"});
            table2.AddRow(new string[] {
                        "Lab Management",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
            table2.AddRow(new string[] {
                        "Manage Laboratories",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
            table2.AddRow(new string[] {
                        "Add Lab",
                        "True",
                        "False",
                        "NA",
                        "NA",
                        "NA"});
            table2.AddRow(new string[] {
                        "Associate Site(s) to Lab",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
            table2.AddRow(new string[] {
                        "Normalize Lab Data",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
            table2.AddRow(new string[] {
                        "Manage Reference Ranges",
                        "NA",
                        "NA",
                        "False",
                        "False",
                        "True"});
#line 23
 testRunner.And("I validate GroupPermissionsData for the premissons group \"Lab Permissions\"", ((string)(null)), table2, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03_Add DataManagers group")]
        public virtual void _03_AddDataManagersGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03_Add DataManagers group", null, ((string[])(null)));
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 34
 testRunner.When("I click breadcrumb \"Group Management\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.And("I click ActionPalette Item \"Add Group(s)\" in \"GroupListActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.Then("I add GroupName \"Data Managers\" with DefaultPortal \"Data Manager Portal\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04_Navigate to Edit Permisssions page of Data Managers Group")]
        public virtual void _04_NavigateToEditPermisssionsPageOfDataManagersGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_Navigate to Edit Permisssions page of Data Managers Group", null, ((string[])(null)));
#line 38
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 39
 testRunner.When("I click GroupName \"Data Managers\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.And("I select status \"Active\" for the permission group and Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.Then("I see expanded PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PermissionName",
                        "Allow",
                        "Deny",
                        "Hide",
                        "View",
                        "Edit"});
            table3.AddRow(new string[] {
                        "Associate Lab(s) to Site",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
#line 44
 testRunner.And("I validate GroupPermissionsData for the premissons group \"Site Permissions\"", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05_Check Default values for Lab Permissions for DataManagers Group")]
        public virtual void _05_CheckDefaultValuesForLabPermissionsForDataManagersGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05_Check Default values for Lab Permissions for DataManagers Group", null, ((string[])(null)));
#line 48
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 49
 testRunner.When("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("I see expanded PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "PermissionName",
                        "Allow",
                        "Deny",
                        "Hide",
                        "View",
                        "Edit"});
            table4.AddRow(new string[] {
                        "Lab Management",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
            table4.AddRow(new string[] {
                        "Manage Laboratories",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
            table4.AddRow(new string[] {
                        "Add Lab",
                        "False",
                        "True",
                        "NA",
                        "NA",
                        "NA"});
            table4.AddRow(new string[] {
                        "Associate Site(s) to Lab",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
            table4.AddRow(new string[] {
                        "Normalize Lab Data",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
            table4.AddRow(new string[] {
                        "Manage Reference Ranges",
                        "NA",
                        "NA",
                        "True",
                        "False",
                        "False"});
#line 51
 testRunner.And("I validate GroupPermissionsData for the premissons group \"Lab Permissions\"", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06_SyncUsers and wait till job finished")]
        public virtual void _06_SyncUsersAndWaitTillJobFinished()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06_SyncUsers and wait till job finished", null, ((string[])(null)));
#line 60
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 61
 testRunner.When("I click breadcrumb \"Group Management\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.And("I click ActionPalette Item \"Synchronize Users\" in \"GroupListActions\" ActionPalett" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.And("I click continue in modal dialog having title \"Synchronize Users\" and partial mes" +
                    "sage \"Synchronizing users\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I click main tab \"Inbox\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Subject"});
            table5.AddRow(new string[] {
                        "Synchronize Users with Reporting - complete. View Summary"});
#line 65
 testRunner.Then("I check subjects in inbox folder \"Jobs\"", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07_Set View permission to Associate Lab(s) to Site in SitePermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _07_SetViewPermissionToAssociateLabSToSiteInSitePermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07_Set View permission to Associate Lab(s) to Site in SitePermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 70
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 71
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I set value in category \"Site Permissions\" for permission \"Associate Lab(s) to Si" +
                    "te\" for permission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I click ActionPalette Item \"Associate Lab(s)\" in \"SiteActions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.Then("I see Associate Labs Page in View mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08_Set Hide permission to Associate Lab(s) to Site in SitePermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _08_SetHidePermissionToAssociateLabSToSiteInSitePermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08_Set Hide permission to Associate Lab(s) to Site in SitePermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 87
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 88
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I set value in category \"Site Permissions\" for permission \"Associate Lab(s) to Si" +
                    "te\" for permission type \"Hide\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.And("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.Then("I do not see ActionPalette Item \"Associate Lab(s)\" in \"SiteActions\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09_Set Deny permission to AddLab in LabPermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _09_SetDenyPermissionToAddLabInLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09_Set Deny permission to AddLab in LabPermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Add Lab\" for permission" +
                    " type \"Deny\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.Then("I do not see ActionPalette Item \"Add Lab\" in \"LabMgmt_Actions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10_Set View permission to Associate Site(s) to Lab in LabPermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _10_SetViewPermissionToAssociateSiteSToLabInLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10_Set View permission to Associate Site(s) to Lab in LabPermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 119
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 120
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Associate Site(s) to La" +
                    "b\" for permission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("I click ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.Then("I see Associate Sites Page in View mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11_Set Hide permission to Associate Site(s) to Lab in LabPermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _11_SetHidePermissionToAssociateSiteSToLabInLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11_Set Hide permission to Associate Site(s) to Lab in LabPermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 137
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 138
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 139
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Associate Site(s) to La" +
                    "b\" for permission type \"Hide\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 146
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.And("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.Then("I do not see ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPa" +
                    "lette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12_Set View permission to Lab Management in LabPermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _12_SetViewPermissionToLabManagementInLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12_Set View permission to Lab Management in LabPermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 154
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 155
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Manage Laboratories\" fo" +
                    "r permission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.And("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.Then("I see Lab page in view mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13_Set Hide permission to Lab Management in LabPermissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _13_SetHidePermissionToLabManagementInLabPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13_Set Hide permission to Lab Management in LabPermissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 172
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 173
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 174
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"Hide\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("I click contineu in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.And("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.Then("I do not see link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14_SetDefault values for Site And Lab Permissions for Admin Group permissions")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _14_SetDefaultValuesForSiteAndLabPermissionsForAdminGroupPermissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14_SetDefault values for Site And Lab Permissions for Admin Group permissions", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 186
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 187
 testRunner.When("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
 testRunner.And("I click GroupName \"EDC Engineering Admins Group\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 191
 testRunner.And("I set value in category \"Site Permissions\" for permission \"Associate Lab(s) to Si" +
                    "te\" for permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 192
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Manage Laboratories\" fo" +
                    "r permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Add Lab\" for permission" +
                    " type \"Allow\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Associate Site(s) to La" +
                    "b\" for permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.And("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I click continue in modal dialog having title \"Edit Permissions\" and partial mess" +
                    "age \"group security you belong to\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.Then("I click continue in reset session modal having partial message \"continue your ses" +
                    "sion\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15_Set Data Manager permission to Allow for Data Managers group")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _15_SetDataManagerPermissionToAllowForDataManagersGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15_Set Data Manager permission to Allow for Data Managers group", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 202
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 203
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 204
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.And("I click GroupName \"Data Managers\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I set value in category \"Site Permissions\" for permission \"Site Management\" for p" +
                    "ermission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Manage Laboratories\" fo" +
                    "r permission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.And("I expand PermissionsGroup \"Portal Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("I set value in category \"Portal Permissions\" for permission \"Data Manager\" for pe" +
                    "rmission type \"Allow\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.Then("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16_Set Study Status to Production in Study Management page")]
        public virtual void _16_SetStudyStatusToProductionInStudyManagementPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16_Set Study Status to Production in Study Management page", null, ((string[])(null)));
#line 216
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 217
 testRunner.When("I click breadcrumb \"Study Administration\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 218
 testRunner.And("I click Link \"Study Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I change study status \"Production\" in Study Management page And Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.And("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17_Login to Datalabs as DataManager user")]
        public virtual void _17_LoginToDatalabsAsDataManagerUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17_Login to Datalabs as DataManager user", null, ((string[])(null)));
#line 223
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 224
 testRunner.Given("I logged in to DataLabs as DataManager user In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 225
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18_Check for Add Lab link availability")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _18_CheckForAddLabLinkAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18_Check for Add Lab link availability", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 228
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 229
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 230
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.Then("I do not see ActionPalette Item \"Add Lab\" in \"LabMgmt_Actions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19_Check for Associate Site(s) link availability")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _19_CheckForAssociateSiteSLinkAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19_Check for Associate Site(s) link availability", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 235
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 236
 testRunner.When("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
 testRunner.Then("I do not see ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPa" +
                    "lette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 238
 testRunner.And("I see Lab page in view mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20_Logout form DataLabs")]
        public virtual void _20_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20_Logout form DataLabs", null, ((string[])(null)));
#line 240
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 241
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 242
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21_Login to Datalabs")]
        public virtual void _21_LoginToDatalabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21_Login to Datalabs", null, ((string[])(null)));
#line 244
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 245
 testRunner.Given("I logged in to DataLabs In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 246
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22_Set LabManagement to Edit, Add Lab to Allow and Associate Site(s) to Lab to Vi" +
            "ew in GroupPermissions for Data Manager")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _22_SetLabManagementToEditAddLabToAllowAndAssociateSiteSToLabToViewInGroupPermissionsForDataManager()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22_Set LabManagement to Edit, Add Lab to Allow and Associate Site(s) to Lab to Vi" +
                    "ew in GroupPermissions for Data Manager", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 249
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 250
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 252
 testRunner.And("I click GroupName \"Data Managers\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 253
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 254
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 255
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 256
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Manage Laboratories\" fo" +
                    "r permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Add Lab\" for permission" +
                    " type \"Allow\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Associate Site(s) to La" +
                    "b\" for permission type \"View\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.Then("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23_Logout form DataLabs")]
        public virtual void _23_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23_Logout form DataLabs", null, ((string[])(null)));
#line 261
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 262
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 263
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24_Login to Datalabs as DataManager user")]
        public virtual void _24_LoginToDatalabsAsDataManagerUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24_Login to Datalabs as DataManager user", null, ((string[])(null)));
#line 265
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 266
 testRunner.Given("I logged in to DataLabs as DataManager user In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 267
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25_Check for Add Lab link availability")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _25_CheckForAddLabLinkAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25_Check for Add Lab link availability", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 270
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 271
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 272
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 273
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.Then("I see ActionPalette Item \"Add Lab\" in \"LabMgmt_Actions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("26_Check for Associate Site(s) link availability and editable Lab Page")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _26_CheckForAssociateSiteSLinkAvailabilityAndEditableLabPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("26_Check for Associate Site(s) link availability and editable Lab Page", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 277
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 278
 testRunner.When("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 279
 testRunner.Then("I see ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPalette", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 280
 testRunner.And("I see Lab page in Edit mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("27_Check for View mode for Associates Labs page")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _27_CheckForViewModeForAssociatesLabsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("27_Check for View mode for Associates Labs page", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 283
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 284
 testRunner.And("I click ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 285
 testRunner.Then("I see Associate Sites Page in View mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("28_Logout form DataLabs")]
        public virtual void _28_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("28_Logout form DataLabs", null, ((string[])(null)));
#line 287
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 288
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 289
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("29_Login to Datalabs")]
        public virtual void _29_LoginToDatalabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("29_Login to Datalabs", null, ((string[])(null)));
#line 291
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 292
 testRunner.Given("I logged in to DataLabs In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 293
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("30_Set LabManagement to Edit, Add Lab to Allow and Associate Site(s) to Lab to Vi" +
            "ew in GroupPermissions for Data Manager")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _30_SetLabManagementToEditAddLabToAllowAndAssociateSiteSToLabToViewInGroupPermissionsForDataManager()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("30_Set LabManagement to Edit, Add Lab to Allow and Associate Site(s) to Lab to Vi" +
                    "ew in GroupPermissions for Data Manager", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 296
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 297
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 298
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 299
 testRunner.And("I click GroupName \"Data Managers\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 301
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 302
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 303
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Manage Laboratories\" fo" +
                    "r permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 304
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Add Lab\" for permission" +
                    " type \"Allow\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 305
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Associate Site(s) to La" +
                    "b\" for permission type \"Edit\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 306
 testRunner.Then("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31_Logout form DataLabs")]
        public virtual void _31_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31_Logout form DataLabs", null, ((string[])(null)));
#line 308
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 309
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 310
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32_Login to Datalabs as DataManager user")]
        public virtual void _32_LoginToDatalabsAsDataManagerUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32_Login to Datalabs as DataManager user", null, ((string[])(null)));
#line 312
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 313
 testRunner.Given("I logged in to DataLabs as DataManager user In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 314
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33_Check for edit mode of page Associate Site(s) to Lab")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _33_CheckForEditModeOfPageAssociateSiteSToLab()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33_Check for edit mode of page Associate Site(s) to Lab", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 317
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 318
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 319
 testRunner.And("I click Link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 320
 testRunner.And("I click Link \"Manage Laboratories\" In Lab Management Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 321
 testRunner.And("I open lab with labid \"L01\" from LabManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 322
 testRunner.And("I click ActionPalette Item \"Associate Site(s)\" in \"LabMgmt_Actions\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 323
 testRunner.Then("I see Associate Sites Page in Edit mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34_Logout form DataLabs")]
        public virtual void _34_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34_Logout form DataLabs", null, ((string[])(null)));
#line 325
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 326
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 327
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35_Login to Datalabs")]
        public virtual void _35_LoginToDatalabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35_Login to Datalabs", null, ((string[])(null)));
#line 329
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 330
 testRunner.Given("I logged in to DataLabs In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 331
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36_Set LabManagement in LabPermissions and Associate Lab(s) in Site Permission to" +
            " Hide for DataManagers group")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _36_SetLabManagementInLabPermissionsAndAssociateLabSInSitePermissionToHideForDataManagersGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36_Set LabManagement in LabPermissions and Associate Lab(s) in Site Permission to" +
                    " Hide for DataManagers group", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 334
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 335
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 336
 testRunner.And("I click Link \"Group Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 337
 testRunner.And("I click GroupName \"Data Managers\" in GroupManagement Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 338
 testRunner.And("I click ActionPalette Item \"Edit Permissions\" in \"GroupDetailsActions\" ActionPale" +
                    "tte", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 339
 testRunner.And("I expand PermissionsGroup \"Lab Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 340
 testRunner.And("I set value in category \"Lab Permissions\" for permission \"Lab Management\" for per" +
                    "mission type \"Hide\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 341
 testRunner.And("I expand PermissionsGroup \"Site Permissions\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 342
 testRunner.And("I set value in category \"Site Permissions\" for permission \"Associate Lab(s) to Si" +
                    "te\" for permission type \"Hide\" in EditPermissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 343
 testRunner.Then("I click save button in edit permissions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("37_Logout form DataLabs")]
        public virtual void _37_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("37_Logout form DataLabs", null, ((string[])(null)));
#line 345
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 346
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 347
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("38_Login to Datalabs as DataManager user")]
        public virtual void _38_LoginToDatalabsAsDataManagerUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("38_Login to Datalabs as DataManager user", null, ((string[])(null)));
#line 349
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 350
 testRunner.Given("I logged in to DataLabs as DataManager user In ExistingPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 351
 testRunner.Then("I see Datalabs Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("39_Check for LabManagement module availability in StudayAdministration Page")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _39_CheckForLabManagementModuleAvailabilityInStudayAdministrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39_Check for LabManagement module availability in StudayAdministration Page", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 354
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 355
 testRunner.When("I select DataManagerPortal item \"Study Administration\" from drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 356
 testRunner.Then("I do not see link \"Lab Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("40_Check for availability of Assocaite Lab(s) to Site link in SitePage")]
        [NUnit.Framework.CategoryAttribute("ObjectiveEvidence")]
        [NUnit.Framework.CategoryAttribute("ReqId:US36590.2")]
        public virtual void _40_CheckForAvailabilityOfAssocaiteLabSToSiteLinkInSitePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40_Check for availability of Assocaite Lab(s) to Site link in SitePage", null, new string[] {
                        "ObjectiveEvidence",
                        "ReqId:US36590.2"});
#line 359
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 361
 testRunner.When("I click Link \"Site Management\" In StudyAdministrationPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 362
 testRunner.And("I open site with siteid \"01\" and site name \"Site\" from SiteManagement page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.Then("I do not see ActionPalette Item \"Associate Lab(s)\" in \"SiteActions\" ActionPalette" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41_Logout form DataLabs")]
        public virtual void _41_LogoutFormDataLabs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41_Logout form DataLabs", null, ((string[])(null)));
#line 365
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 366
 testRunner.When("I clik logout of Datalabs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 367
 testRunner.Then("I see login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

